// Code generated by sadayuki-matsuno bob-ex. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "github.com/stephenafamo/bob"

// Make sure the type Comment runs hooks after queries
var _ bob.HookableType = &Comment{}

// Make sure the type PostTag runs hooks after queries
var _ bob.HookableType = &PostTag{}

// Make sure the type Post runs hooks after queries
var _ bob.HookableType = &Post{}

// Make sure the type Tag runs hooks after queries
var _ bob.HookableType = &Tag{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}
