// Code generated by sadayuki-matsuno bob-ex. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models_test

import (
	models "github.com/sadayuki-matsuno/bob-example/example/models"
	"github.com/stephenafamo/bob"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor

// Make sure the type Comment runs hooks after queries
var _ bob.HookableType = &models.Comment{}

// Make sure the type PostTag runs hooks after queries
var _ bob.HookableType = &models.PostTag{}

// Make sure the type Post runs hooks after queries
var _ bob.HookableType = &models.Post{}

// Make sure the type Tag runs hooks after queries
var _ bob.HookableType = &models.Tag{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &models.User{}
